### PR TITLE
Feature/role influxdb enable https

### PR DESCRIPTION
**Pull request by paasi6666**
Feature added to enable HTTPS (optional).

### CODE REVIEW

**Comment by NavidSassan** [comment]
Hi, thanks for the PR! I simplified the variables a bit, as we don't need to set multiple certificates, just one :)
I also separated `validate_certs` into its own variable as it is not part of the config and only changes the behaviour of the role. Please check if these changes still work for your use case.

**Comment by paasi6666** [comment]
> Hi, thanks for the PR! I simplified the variables a bit, as we don't need to set multiple certificates, just one :) I also separated `validate_certs` into its own variable as it is not part of the config and only changes the behaviour of the role. Please check if these changes still work for your use case.

Thanks for the simplifications. Almost worked for our use case (minor changes, already commited).

**Comment by NavidSassan** [comment]
Did you get a bug without your changes? If so, can you send me the error and your ansible version? In general, the `> 1` comparison should not be needed, any number other than 0 is "truthy" in python.

**Comment by paasi6666** [comment]
> Did you get a bug without your changes? If so, can you send me the error and your ansible version? In general, the `> 1` comparison should not be needed, any number other than 0 is "truthy" in python.

In the influxdb.yml it will just puts a `2` instead of `true`:
```
  # Determines whether HTTPS is enabled.
  https-enabled = 2
```

And in the task, it tells me the following:
`TASK [linuxfabrik.lfops.influxdb : create new admin user "influxdb-admin"] *****
fatal: [p-vm-graf-002.stadtluzern.ch]: FAILED! => {"changed": false, "msg": "400: Client sent an HTTP request to an HTTPS server.\n"}`

Verbose output:
```
fatal: [server@domain.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin": true,
            "grants": null,
            "hostname": "localhost",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "",
            "port": 8086,
            "proxies": {},
            "retries": 3,
            "ssl": false,
            "state": "present",
            "timeout": null,
            "udp_port": 4444,
            "use_udp": false,
            "user_name": "influxdb-admin",
            "user_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "influxdb-admin",
            "validate_certs": false
        }
    },
    "msg": "400: Client sent an HTTP request to an HTTPS server.\n"
```

**Comment by NavidSassan** [comment]
thanks a lot for your contribution!

**Pull request merged**
